/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        app: {
          bg: 'var(--app-bg)',
          surface: 'var(--app-surface)',
          border: 'var(--app-border)',
          text: 'var(--app-text)',
          'text-strong': 'var(--app-text-strong)',
          muted: 'var(--app-text-muted)',
          soft: 'var(--app-text-soft)',
          accent: 'var(--app-accent)',
          'accent-strong': 'var(--app-accent-strong)',
          success: 'var(--app-success-text)',
          danger: 'var(--app-danger-text)',
        },
        background: 'var(--auth-background)',
        'inverse-on-surface': 'var(--auth-inverse-on-surface)',
        'inverse-primary': 'var(--auth-inverse-primary)',
        'inverse-surface': 'var(--auth-inverse-surface)',
        outline: 'var(--auth-outline)',
        'outline-variant': 'var(--auth-outline-variant)',
        primary: 'var(--auth-primary)',
        'primary-container': 'var(--auth-primary-container)',
        'primary-fixed': 'var(--auth-primary-fixed)',
        'primary-fixed-dim': 'var(--auth-primary-fixed-dim)',
        secondary: 'var(--auth-secondary)',
        'secondary-container': 'var(--auth-secondary-container)',
        'secondary-fixed': 'var(--auth-secondary-fixed)',
        'secondary-fixed-dim': 'var(--auth-secondary-fixed-dim)',
        surface: 'var(--auth-surface)',
        'surface-bright': 'var(--auth-surface-bright)',
        'surface-container': 'var(--auth-surface-container)',
        'surface-container-high': 'var(--auth-surface-container-high)',
        'surface-container-highest': 'var(--auth-surface-container-highest)',
        'surface-container-low': 'var(--auth-surface-container-low)',
        'surface-container-lowest': 'var(--auth-surface-container-lowest)',
        'surface-dim': 'var(--auth-surface-dim)',
        'surface-tint': 'var(--auth-surface-tint)',
        'surface-variant': 'var(--auth-surface-variant)',
        tertiary: 'var(--auth-tertiary)',
        'tertiary-container': 'var(--auth-tertiary-container)',
        'tertiary-fixed': 'var(--auth-tertiary-fixed)',
        'tertiary-fixed-dim': 'var(--auth-tertiary-fixed-dim)',
        'on-background': 'var(--auth-on-background)',
        'on-error': 'var(--auth-on-error)',
        'on-error-container': 'var(--auth-on-error-container)',
        'on-primary': 'var(--auth-on-primary)',
        'on-primary-container': 'var(--auth-on-primary-container)',
        'on-primary-fixed': 'var(--auth-on-primary-fixed)',
        'on-primary-fixed-variant': 'var(--auth-on-primary-fixed-variant)',
        'on-secondary': 'var(--auth-on-secondary)',
        'on-secondary-container': 'var(--auth-on-secondary-container)',
        'on-secondary-fixed': 'var(--auth-on-secondary-fixed)',
        'on-secondary-fixed-variant': 'var(--auth-on-secondary-fixed-variant)',
        'on-surface': 'var(--auth-on-surface)',
        'on-surface-variant': 'var(--auth-on-surface-variant)',
        'on-tertiary': 'var(--auth-on-tertiary)',
        'on-tertiary-container': 'var(--auth-on-tertiary-container)',
        'on-tertiary-fixed': 'var(--auth-on-tertiary-fixed)',
        'on-tertiary-fixed-variant': 'var(--auth-on-tertiary-fixed-variant)',
      },
      backgroundImage: {
        'app-shell': 'var(--app-shell-bg)',
        'app-frame': 'var(--app-frame-bg)',
        'app-panel': 'var(--app-panel-bg)',
        'app-hero': 'var(--app-hero-bg)',
        'app-progress': 'var(--app-progress-fill)',
      },
      borderRadius: {
        'app-lg': 'var(--app-radius-lg)',
        'app-xl': 'var(--app-radius-xl)',
        'app-2xl': 'var(--app-radius-2xl)',
      },
      boxShadow: {
        'app-frame': 'var(--app-shadow-soft)',
        'app-card': 'var(--app-shadow-card)',
        'app-hero': 'var(--app-hero-shadow)',
      },
      spacing: {
        base: '8px',
        gutter: '16px',
        lg: '40px',
        'margin-desktop': '48px',
        'margin-mobile': '20px',
        md: '24px',
        sm: '12px',
        xl: '64px',
        xs: '4px',
      },
      fontFamily: {
        'body-lg': ['Plus Jakarta Sans'],
        'body-md': ['Plus Jakarta Sans'],
        'headline-lg': ['Plus Jakarta Sans'],
        'headline-md': ['Plus Jakarta Sans'],
        'headline-xl': ['Plus Jakarta Sans'],
        'label-md': ['Plus Jakarta Sans'],
        'label-sm': ['Plus Jakarta Sans'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
}
